name = "cf-emby-proxy-ui" # Worker 的项目名称
main = "worker.js" # Worker 的主入口文件
compatibility_date = "2026-03-13" # 兼容性日期，用于指定使用的 Cloudflare 运行时版本
keep_vars = true

# KV 命名空间绑定声明 (KV Namespace Binding)
[[kv_namespaces]]
binding = "ENI_KV" # 代码中调用该 KV 的变量名
id = "36c8af13dd8a4dd5b2fb4eec04f22e52" # 你的 KV 命名空间 ID (请替换为实际的 32 位字母数字组合)

# D1 数据库绑定声明 (D1 Database Binding)
[[d1_databases]]
binding = "DB" # 代码中调用该数据库的变量名
database_name = "emby_proxy_logs" # 你的 D1 数据库的名称
database_id = "76b66499-b3bc-4d17-9db6-85d0e0cd11f2" # 你的 D1 数据库 ID (请替换为实际的 UUID 格式)
